### ISSUE TITLE
[1.4] Spamming  errors in console

### ISSUE THREAD

**Issue by BillZhucn** [arboriginal/Chair#6]
**Step 1: Read this first**
If you don't read and apply what is explained here, don't waste your time to post: I'll simply ignore it!

If you're too lazy for it, I will be lazy too. I'm making my plugins on my free time (and it takes time), I'm sharing them with the community and ask no money for this. So, if you don't understand I'm bored by people who makes me loose my time, then don't use my plugins and don't disturb me.

Also, remember if you don't give enough details, I will not be able to reproduce, and I can't work on a bug I can't see. It's also humanly impossible to try all possible combinations of configurations / installed plugins / versions, so don't count on me to pass hours to check everything for you.

Keep in mind I have several parallel projects (what you see from me on Github and Spigot is not all I'm doing) and, believe it or not... I have a life aside plugins development and Minecraft, with adult responsibilities and everything. So, if I'm not replying / fixing quickly, wait patiently. I'll do my best but there is sometimes more important / urgent. Being upset will not help and worse, it could demotivate me to help you.

For all of you who will follow this bug report guideline, I'll do my best to help you as soon as I can. And if you have java knowledge, do not hesitate to send me a pull request on github if you know how to fix something or improve the plugin.

Sorry for this long process but because of users, unable to read 3 lines on the bottom of my plugin descriptions where I explained this shortly, I no more want to loose my time by explaining again and again the same things. Asking again and again the same details, waiting to get a part of them, re-ask, etc to finally after loosing my energy to get enough informations to start debug and release a fixed version, don't receive even a single word to confirm me it's ok now. If you're still reading this I suppose you are smart enough to understand that, and this is exclusively for people like you I'm going on to share my plugins.

Do not hesitate to leave a comment, in Github and in Spigot forum, when a user post an incomplete bug report to ask him to report correctly, or to shut up. I let you choose your words (within the limits of Github / Spigot rules). This small action will help me not being depressive and not give up the sharing of my plugins.

**Step 2: Verifications**
Because the problem can be with your configuration or another plugin:

0. Check if a similar issue exists, if yes, don't create a duplicate but add a comment to it
1. Re-read plugin description and documentation
2. Backup your actual configuration
3. Remove my plugin configuration and restart your server (so a fresh config is generated)
4. Try to change one parameter and test, change a second one and test, ...
5. Try without your other plugins
6. Re-add your plugins one by one and re-test each time to determine if there is an incompatibility
7. If you didn't solved the problem, fill this report, and delete all lines above "Describe the bug".
8. Choose a comprehensive title which shortly describes the problem, prefixed by the exact version of the plugin, for example: « [1.0] ».
9. Remove text after "Additional context" question

You are allowed to skip some questions IF AND ONLY IF it's not applicable / relevant (and in this case, remove them, no need to let the default text!). BTW... English is not my mother language, so do not use sentences too complex for a non-native english.

**Describe the bug**
Just the errors found in the console.
**To Reproduce**
Steps to reproduce the behavior. Basically, if it's not happen, there is no bug.
I have no idea because there are nothing else strange in the log.
**Expected behavior**
I just saw the errors and I do not know the behaviour in game.(No player report wired behavior to me)
**Screenshots**

**Environment**
 - Java version
java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
 - Spigot / Paper version
[21:07:14 INFO]: This server is running Paper version git-Paper-126 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:07:14 INFO]: Checking version, please wait...
[21:07:16 INFO]: Previous version: git-Paper-122 (MC: 1.15.2)
[21:07:16 INFO]: You are 3 version(s) behind
 - Plugin version (beware, "latest" is not a version)
1.4
 - Plugin configuration https://gist.github.com/BillZhucn/8fb63c91d9dd80ef978abc21a8226da9#file-chair-config-yml
 - Error log (same, use Gist, pastebin or similar) 
https://gist.github.com/BillZhucn/6a09aa7768c6dda7c922259c9d6b10aa#file-errors-in-console
 - main parameters of your server (ones that can have impact with the plugin)

**Additional context**
---

By submitting this issue, you confirm having read, understand and accepted its guideline.
You also confirm having a functional brain activated during the writing of this issue.

**Comment by arboriginal** [comment]
You should remove lines as mentioned in points 7 & 9 and remove description texts of questions, the bug report will be much easier to read, but at least I have informations.

I never had this kind of errors, even if I'm using Paper too (re-checked with 129 without issues). I've skipped some versions so maybe it could be related: Some of them talk about teleporting dead entities fixes in the changelog.

I recommend you to update your paper version to the last one. If it doesn't solve your problem, re-check "verifications" point as I've no idea which plugins you are using... And again, if I can't reproduce, I can't fix it.
